version: '3.1'

services:
  mongodb:
    image: library/mongo:4.4.0-bionic # https://hub.docker.com/_/mongo
    ports:
      - "27117:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: openlibrary
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js