spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:pass123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:openlibrary}?authSource=${MONGO_AUTH_DB:admin}
      auto-index-creation: true
booklink:
  data-importer:
    frequency-check: ${BOOKLINK_FREQUENCY_CHECK:10}
    persist: ${BOOKLINK_PERSIST:false}