name: snapshot

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/snapshot.yml'

env:
  DOCKER_IMAGE: docker.io/mrazjava/booklink-openlibrary-depot
  DOCKER_IMG_TAG: develop
  ARTIFACT_DIR: snapshot_${{ github.sha }}

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[skip-ci]') == false
    runs-on: ubuntu-latest
    name: Test and Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: setup jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: test, then build jar
        id: mvn-jar
        run: |
          mvn -B clean verify
      - name: upload jar artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DIR }}
          path: target/booklink-openlibrary.jar
      - name: upload dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DIR }}
          path: Dockerfile
  publish:
    runs-on: ubuntu-latest
    name: Package and Deploy
    needs: build
    steps:
      - name: download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_DIR }}
      - name: assemble docker image
        id: dockerize
        run: |
          mkdir -p target
          mv $ARTIFACT_DIR/booklink-openlibrary.jar target/
          mv $ARTIFACT_DIR/Dockerfile .
          docker build -t $DOCKER_IMAGE:$DOCKER_IMG_TAG .
      - name: push snapshot image to dockerhub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io
          docker push $DOCKER_IMAGE:$DOCKER_IMG_TAG